import { Presentation } from "@/pages/tutor/presentations/presentation";

export const mockPresentations: Presentation[] = [
  {
    id: "1",
    studentName: "Maria Rossi",
    courseName: "Nozioni di base sulla nutrizione",
    moduleName: "Modulo 2",
    type: "Caso di studio",
    date: "15 settembre 2025",
    status: "pending",
    fileName: "caso_studio_maria.pdf",
    fileSize: "2,4 MB",
    uploadDate: "15 settembre 2025",
  },
  {
    id: "2",
    studentName: "John Smith",
    courseName: "Forza e condizionamento",
    moduleName: "Quiz 1",
    type: "Quiz",
    date: "14 settembre 2025",
    status: "approved",
    fileName: "quiz_john.pdf",
    fileSize: "1,2 MB",
    uploadDate: "14 settembre 2025",
  },
  {
    id: "3",
    studentName: "Sarah Lee",
    courseName: "Scienze Motorie",
    moduleName: "Esame finale",
    type: "Esame",
    date: "10 settembre 2025",
    status: "rejected",
    fileName: "esame_sarah.pdf",
    fileSize: "3,1 MB",
    uploadDate: "10 settembre 2025",
  },
  {
    id: "4",
    studentName: "Marco Bianchi",
    courseName: "Nutrizione Sportiva",
    moduleName: "Modulo 3",
    type: "Caso di studio",
    date: "12 settembre 2025",
    status: "pending",
    fileName: "caso_studio_marco.pdf",
    fileSize: "1,8 MB",
    uploadDate: "12 settembre 2025",
  },
  {
    id: "5",
    studentName: "Emma Wilson",
    courseName: "Personal Training",
    moduleName: "Quiz 2",
    type: "Quiz",
    date: "11 settembre 2025",
    status: "approved",
    fileName: "quiz_emma.pdf",
    fileSize: "0,9 MB",
    uploadDate: "11 settembre 2025",
  },
  {
    id: "6",
    studentName: "Luca Ferrari",
    courseName: "Anatomia",
    moduleName: "Esame finale",
    type: "Esame",
    date: "9 settembre 2025",
    status: "rejected",
    fileName: "esame_luca.pdf",
    fileSize: "2,7 MB",
    uploadDate: "9 settembre 2025",
  },
];
